import nodemailer from "nodemailer";

function getTransporter() {
  const host = process.env["SMTP_HOST"];
  const port = parseInt(process.env["SMTP_PORT"] || "587", 10);
  const user = process.env["SMTP_USER"];
  const pass = process.env["SMTP_PASS"];

  if (host && host !== "localhost") {
    return nodemailer.createTransport({
      host,
      port,
      secure: port === 465,
      auth: user && pass ? { user, pass } : undefined,
    });
  }

  return nodemailer.createTransport({
    host: "localhost",
    port: 1025,
    ignoreTLS: true,
  });
}

export async function sendPayslipEmail(options: {
  to: string;
  subject: string;
  html: string;
  from?: string;
}): Promise<void> {
  const transporter = getTransporter();
  const from = options.from || process.env["EMAIL_FROM"] || "noreply@kenyapay.co.ke";

  await transporter.sendMail({
    from,
    to: options.to,
    subject: options.subject,
    html: options.html,
  });
}

export function buildPayslipHtml(payslip: {
  employeeName: string;
  employeeNumber: string;
  month: string;
  year: number;
  grossSalary: number;
  basicSalary: number;
  paye: number;
  nssfEmployee: number;
  nssfEmployer: number;
  shif: number;
  housingLevyEmployee: number;
  housingLevyEmployer: number;
  personalRelief: number;
  netPay: number;
  companyName?: string;
  companyAddress?: string;
  kraPin?: string;
}): string {
  const format = (n: number) => `KES ${n.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="text-align: center; margin-bottom: 24px;">
    ${payslip.companyName ? `<h2 style="margin:0">${payslip.companyName}</h2>` : ""}
    ${payslip.companyAddress ? `<p style="margin:4px 0;color:#666">${payslip.companyAddress}</p>` : ""}
    ${payslip.kraPin ? `<p style="margin:4px 0;color:#666">KRA PIN: ${payslip.kraPin}</p>` : ""}
    <h3 style="margin-top:16px">Payslip for ${payslip.month} ${payslip.year}</h3>
  </div>
  <div style="margin-bottom:16px;padding:12px;background:#f5f5f5;border-radius:6px;">
    <strong>${payslip.employeeName}</strong> — ${payslip.employeeNumber}
  </div>
  <table style="width:100%;border-collapse:collapse;">
    <tr><td style="padding:8px 0;border-bottom:1px solid #ddd;">Gross Salary</td><td style="text-align:right;padding:8px 0;border-bottom:1px solid #ddd;">${format(payslip.grossSalary)}</td></tr>
    <tr><td style="padding:8px 0;border-bottom:1px solid #ddd;">Basic Salary</td><td style="text-align:right;padding:8px 0;border-bottom:1px solid #ddd;">${format(payslip.basicSalary)}</td></tr>
    <tr><td style="padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">PAYE</td><td style="text-align:right;padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">-${format(payslip.paye)}</td></tr>
    <tr><td style="padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">NSSF (Employee)</td><td style="text-align:right;padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">-${format(payslip.nssfEmployee)}</td></tr>
    <tr><td style="padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">SHIF</td><td style="text-align:right;padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">-${format(payslip.shif)}</td></tr>
    <tr><td style="padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">Housing Levy</td><td style="text-align:right;padding:8px 0;border-bottom:1px solid #ddd;color:#c00;">-${format(payslip.housingLevyEmployee)}</td></tr>
    <tr><td style="padding:8px 0;color:#090;">Personal Relief</td><td style="text-align:right;padding:8px 0;color:#090;">+${format(payslip.personalRelief)}</td></tr>
    <tr style="font-weight:bold;font-size:1.1em;">
      <td style="padding:12px 0;border-top:2px solid #333;">Net Pay</td>
      <td style="text-align:right;padding:12px 0;border-top:2px solid #333;">${format(payslip.netPay)}</td>
    </tr>
  </table>
  <div style="margin-top:24px;font-size:12px;color:#999;text-align:center;border-top:1px solid #eee;padding-top:12px;">
    This is a computer-generated payslip. Generated by Kenya Payroll Pro.
  </div>
</body>
</html>`;
}
